# Preprocessing

In [1]:
import pandas as pd

### The travel area data

In [7]:
ds_path = '../dataset_2023'

In [18]:
tn_visit_area_info = pd.read_csv(ds_path + '/Training/TL_csv/tn_visit_area_info_방문지정보_E.csv')

In [19]:
# Remove the rows that is not a travel area (ref. E_capital_model.py)
# See tc_codeb_코드B.csv for the meaning of the codes
tn_visit_area_info_travel = tn_visit_area_info[(tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 1) |
   (tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 2) |(tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 3) | (tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 4) |
   (tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 5) | (tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 6) |(tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 7) |
   (tn_visit_area_info['VISIT_AREA_TYPE_CD'] == 8)]
# tn_visit_area_info_travel = tn_visit_area_info_travel.groupby('VISIT_AREA_NM').filter(lambda x: len(x) > 1)
tn_visit_area_info_travel.head()

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
1,2304300002,e_e000004,2,화성 관광열차 안내소 연무대 매표소,2023-04-30,2023-04-30,경기 수원시 팔달구 창룡대로103번길 20,경기 수원시 팔달구 매향동 3-32,127.023339,37.287878,...,동대문종합시장 악세서리부자재시장,60.0,2,N,10.0,NaN,4.0,3.0,4.0,NaN
2,2304300003,e_e000004,3,창룡문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 남수동,127.025143,37.287791,...,창룡문,30.0,2,N,1.0,NaN,4.0,4.0,4.0,NaN
3,2304300004,e_e000004,4,수원 화성 화홍문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 북수동 9000-1,127.017626,37.287546,...,수원화성 화홍문,60.0,2,N,10.0,NaN,4.0,3.0,3.0,NaN
8,2304300004,e_e000006,4,경춘선 자전거길,2023-04-30,2023-04-30,NaN,경기 가평군 청평면 하천리 158-2,127.436200,37.745958,...,경춘선자전거길,150.0,1,Y,4.0,NaN,5.0,5.0,5.0,NaN
17,2304290002,e_e000009,2,농협안성팜랜드,2023-04-29,2023-04-29,경기 안성시 공도읍 대신두길 28,경기 안성시 공도읍 신두리 451,127.193517,36.991317,...,안성팜랜드,30.0,6,N,1.0,NaN,4.0,4.0,4.0,NaN

In [21]:
tn_visit_area_info_travel = (tn_visit_area_info_travel[
    tn_visit_area_info_travel['ROAD_NM_ADDR'].notna() |
    tn_visit_area_info_travel['LOTNO_CD'].notna() |
    tn_visit_area_info_travel['POI_ID'].notna()])
tn_visit_area_info_travel.head()

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
1,2304300002,e_e000004,2,화성 관광열차 안내소 연무대 매표소,2023-04-30,2023-04-30,경기 수원시 팔달구 창룡대로103번길 20,경기 수원시 팔달구 매향동 3-32,127.023339,37.287878,...,동대문종합시장 악세서리부자재시장,60.0,2,N,10.0,NaN,4.0,3.0,4.0,NaN
2,2304300003,e_e000004,3,창룡문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 남수동,127.025143,37.287791,...,창룡문,30.0,2,N,1.0,NaN,4.0,4.0,4.0,NaN
3,2304300004,e_e000004,4,수원 화성 화홍문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 북수동 9000-1,127.017626,37.287546,...,수원화성 화홍문,60.0,2,N,10.0,NaN,4.0,3.0,3.0,NaN
8,2304300004,e_e000006,4,경춘선 자전거길,2023-04-30,2023-04-30,NaN,경기 가평군 청평면 하천리 158-2,127.436200,37.745958,...,경춘선자전거길,150.0,1,Y,4.0,NaN,5.0,5.0,5.0,NaN
17,2304290002,e_e000009,2,농협안성팜랜드,2023-04-29,2023-04-29,경기 안성시 공도읍 대신두길 28,경기 안성시 공도읍 신두리 451,127.193517,36.991317,...,안성팜랜드,30.0,6,N,1.0,NaN,4.0,4.0,4.0,NaN

In [22]:
# Save the cleaned data
tn_visit_area_info_travel.to_csv('./tn_visit_area_info_travel.csv', index=False)

### The travel data

In [ ]:
tn_travel = pd.read_csv(ds_path + '/Training/TL_csv/tn_travel_여행_E.csv')

### The interaction matrix

# Light Factorization Machine Example
ref. https://github.com/recommenders-team/recommenders/blob/main/examples/02_model_collaborative_filtering/fm_deep_dive.ipynb  
ref. https://github.com/recommenders-team/recommenders/blob/main/examples/02_model_collaborative_filtering/lightfm_deep_dive.ipynb